from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.labelNamaBarang = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelNamaBarang.setObjectName("labelNamaBarang")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelNamaBarang)
        self.lineNamaBarang = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineNamaBarang.setObjectName("lineNamaBarang")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.lineNamaBarang)
        self.labelKategori = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelKategori.setObjectName("labelKategori")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelKategori)
        self.comboKategori = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboKategori.setObjectName("comboKategori")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboKategori)
        self.labelTanggal = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelTanggal.setObjectName("labelTanggal")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelTanggal)
        self.dateTanggalMasuk = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.dateTanggalMasuk.setCalendarPopup(True)
        self.dateTanggalMasuk.setObjectName("dateTanggalMasuk")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.dateTanggalMasuk)
        self.labelStatus = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelStatus.setObjectName("labelStatus")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelStatus)
        self.comboStatus = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboStatus.setObjectName("comboStatus")
        self.comboStatus.addItem("")
        self.comboStatus.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.comboStatus)
        self.labelCatatan = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelCatatan.setObjectName("labelCatatan")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelCatatan)
        self.plainCatatan = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.plainCatatan.setObjectName("plainCatatan")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.plainCatatan)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.btnTambah = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnTambah.setObjectName("btnTambah")
        self.buttonLayout.addWidget(self.btnTambah)
        self.btnEdit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnEdit.setObjectName("btnEdit")
        self.buttonLayout.addWidget(self.btnEdit)
        self.btnHapus = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnHapus.setObjectName("btnHapus")
        self.buttonLayout.addWidget(self.btnHapus)
        self.verticalLayout.addLayout(self.buttonLayout)
        self.searchLayout = QtWidgets.QHBoxLayout()
        self.searchLayout.setObjectName("searchLayout")
        self.lineSearch = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineSearch.setObjectName("lineSearch")
        self.searchLayout.addWidget(self.lineSearch)
        self.btnCari = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCari.setObjectName("btnCari")
        self.searchLayout.addWidget(self.btnCari)
        self.verticalLayout.addLayout(self.searchLayout)
        self.tableInventory = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableInventory.setObjectName("tableInventory")
        self.tableInventory.setColumnCount(0)
        self.tableInventory.setRowCount(0)
        self.verticalLayout.addWidget(self.tableInventory)
        self.btnExportCSV = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnExportCSV.setObjectName("btnExportCSV")
        self.verticalLayout.addWidget(self.btnExportCSV)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(parent=self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSimpan = QtGui.QAction(parent=MainWindow)
        self.actionSimpan.setObjectName("actionSimpan")
        self.actionEkspor = QtGui.QAction(parent=MainWindow)
        self.actionEkspor.setObjectName("actionEkspor")
        self.actionKeluar = QtGui.QAction(parent=MainWindow)
        self.actionKeluar.setObjectName("actionKeluar")
        self.actionTentang = QtGui.QAction(parent=MainWindow)
        self.actionTentang.setObjectName("actionTentang")
        self.menuFile.addAction(self.actionSimpan)
        self.menuFile.addAction(self.actionEkspor)
        self.menuFile.addAction(self.actionKeluar)
        self.menuHelp.addAction(self.actionTentang)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Inventory Management Mini App"))
        self.labelNamaBarang.setText(_translate("MainWindow", "Nama Barang:"))
        self.labelKategori.setText(_translate("MainWindow", "Kategori:"))
        self.labelTanggal.setText(_translate("MainWindow", "Tanggal Masuk:"))
        self.labelStatus.setText(_translate("MainWindow", "Status Stok:"))
        self.comboStatus.setItemText(0, _translate("MainWindow", "Tersedia"))
        self.comboStatus.setItemText(1, _translate("MainWindow", "Habis"))
        self.labelCatatan.setText(_translate("MainWindow", "Catatan:"))
        self.btnTambah.setText(_translate("MainWindow", "Tambah"))
        self.btnEdit.setText(_translate("MainWindow", "Edit"))
        self.btnHapus.setText(_translate("MainWindow", "Hapus"))
        self.lineSearch.setPlaceholderText(_translate("MainWindow", "Cari nama/kategori..."))
        self.btnCari.setText(_translate("MainWindow", "Cari"))
        self.btnExportCSV.setText(_translate("MainWindow", "Ekspor ke CSV"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionSimpan.setText(_translate("MainWindow", "Simpan"))
        self.actionEkspor.setText(_translate("MainWindow", "Ekspor ke CSV"))
        self.actionKeluar.setText(_translate("MainWindow", "Keluar"))
        self.actionTentang.setText(_translate("MainWindow", "Tentang"))
